"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
import os
from .base import *

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&$b9qfvh2xy#^9-r%hux&nvs80tqz1t3v^a%*(93c$_+_%*y1j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

# 创建数据库：create database mysite_db default charset=utf8 default collate utf8_unicode_ci;
# 创建用户：create user 'neinei'@'localhost' identified by 'neinei0818';
# 权限：grant all privileges on mysite_db.* to 'neinei'@'localhost';
# flush privilleges;
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mysite_db',
        'USER': 'neinei',
        'PASSWORD': 'neinei0818',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}
